Numerical Processing: Np\core\lapack Class Reference
Np\core\lapack Class Reference
Static Public Member Functions
static geev (\Np\matrix $mat, \Np\vector $wr, \Np\vector $wi, \Np\matrix $vr, int $matLayout=self::ROW_MAJOR)
static gesdd (\Np\matrix $mat, \Np\vector $s, \Np\matrix $u, \Np\matrix $vt, int $matLayout=self::ROW_MAJOR)
static getrf (\Np\matrix $mat, \Np\vector $ipiv, int $matLayout=self::ROW_MAJOR)
static getri (\Np\matrix $mat, \Np\vector $ipiv, int $matLayout=self::ROW_MAJOR)
static init ()
static lange (string $norm, \Np\matrix $m, int $matLayout=self::ROW_MAJOR)
static potrf (\Np\matrix $mat, $uplo=self::Lower, int $matLayout=self::ROW_MAJOR)
static sgels ()
static sort (\Np\vector $v, $id=self::INCR)
static syev (\Np\matrix $mat, \Np\vector $wr, int $matLayout=self::ROW_MAJOR)
Public Attributes
const COL_MAJOR = 102
const DECR = 'D'
const INCR = 'I'
const Lower = 'L'
const ROW_MAJOR = 101
const Upper = 'U'
Static Public Attributes
static $ffi_lapack
Member Function Documentation
geev()
static Np\core\lapack::geev (\Np\matrix $mat, \Np\vector $wr, \Np\vector $wi, \Np\matrix $vr, int $matLayout = self::ROW_MAJOR) static
Parameters
\Np\matrix $mat
\Np\vector $wr
\Np\vector $wi
\Np\matrix $vr
int $matLayout
Returns
int
gesdd()
static Np\core\lapack::gesdd (\Np\matrix $mat, \Np\vector $s, \Np\matrix $u, \Np\matrix $vt, int $matLayout = self::ROW_MAJOR) static
Parameters
\Np\matrix $mat
\Np\vector $s
\Np\matrix $u
\Np\matrix $vt
int $matLayout
Returns
int
Referenced by Np\decompositions\svd\factory().
getrf()
static Np\core\lapack::getrf (\Np\matrix $mat, \Np\vector $ipiv, int $matLayout = self::ROW_MAJOR) static
Parameters
\Np\matrix $mat
\Np\vector $ipiv
int $matLayout
Returns
int
Referenced by Np\reductions\ref\factory(), and Np\decompositions\lu\factory().
getri()
static Np\core\lapack::getri (\Np\matrix $mat, \Np\vector $ipiv, int $matLayout = self::ROW_MAJOR) static
Parameters
\Np\matrix $mat
\Np\vector $ipiv
int $matLayout
Returns
int
lange()
static Np\core\lapack::lange (string $norm, \Np\matrix $m, int $matLayout = self::ROW_MAJOR) static
Parameters
string $norm
\Np\matrix $m
int $matLayout
Returns
potrf()
static Np\core\lapack::potrf (\Np\matrix $mat, $uplo = self::Lower, int $matLayout = self::ROW_MAJOR) static
Parameters
\Np\matrix $mat
string $uplo
int $matLayout
Returns
int
Referenced by Np\decompositions\cholesky\factory().
sort()
static Np\core\lapack::sort (\Np\vector $v, $id = self::INCR) static
Parameters
\Np\vector $v
$id
Returns
syev()
static Np\core\lapack::syev (\Np\matrix $mat, \Np\vector $wr, int $matLayout = self::ROW_MAJOR) static
Parameters
\Np\matrix $mat
\Np\vector $wr
int $matLayout
Returns
int
The documentation for this class was generated from the following file:
/home/ghost/projects/git/numphp/src/core/lapack.php