Numerical Processing: Np\vector Class Reference
Np\vector Class Reference
Public Member Functions
__toString ()
add (int|float|matrix|vector $d)
argMax ()
argMin ()
asArray ()
convolve (\Np\vector $v, int $stride=1)
divide (int|float|matrix|vector $d)
dotMatrix (\Np\matrix $m)
getDtype ()
getSize ()
inner (\Np\vector $vector)
max ()
mean ()
median ()
min ()
mod (int|float|\Np\matrix|\Np\vector $d)
multiply (int|float|matrix|vector $d)
normL1 ()
normL2 ()
normMax ()
normP (float $p=2.5)
pow (int|float|\Np\matrix|\Np\vector $d)
printVector ()
product ()
reciprocal ()
setData (int|float|array $data)
sort ($type='i')
square ()
subtract (int|float|matrix|vector $d)
sum ()
variance ($mean=null)
Public Member Functions inherited from Np\core\nd
checkDimensions (\Np\matrix|\Np\vector $Obj1, \Np\matrix $Obj2)
checkDtype (\Np\matrix|\Np\vector $Obj1, \Np\matrix|\Np\vector $Obj2)
checkShape (\Np\matrix|\Np\vector $Obj1, \Np\matrix|\Np\vector $Obj2)
getMemory ()
time ()
Static Public Member Functions
static ar (array $data, int $dtype=self::FLOAT)
static factory (int $col, int $dtype=self::FLOAT)
static full (int $col, int|float $val, int $dtype=self::FLOAT)
static gaussian (int $n, int $dtype=self::FLOAT)
static linspace (float $min, float $max, int $n, int $dtype=self::FLOAT)
static null (int $col, int $dtype=self::FLOAT)
static ones (int $col, int $dtype=self::FLOAT)
static poisson (int $n, float $lambda=1.0, int $dtype=self::FLOAT)
static randn (int $col, int $dtype=self::FLOAT)
static range (int|float $start, int|float $end, int|float $interval=1, int $dtype=self::FLOAT)
static uniform (int $col, int $dtype=self::FLOAT)
static zeros (int $col, int $dtype=self::FLOAT)
Protected Member Functions
__construct (public int $col, int $dtype=self::FLOAT)
addMatrix (\Np\matrix $m)
addScalar (int|float $s)
addVector (\Np\vector $vector)
divideMatrix (\Np\matrix $m)
divideScalar (int|float $s)
divideVector (vector $v)
modMatrix (\Np\matrix $m)
modScalar (int|float $s)
modVector (\Np\vector $vector)
multiplyMatrix (\Np\matrix $m)
multiplyScalar (int|float $s)
multiplyVector (\Np\vector $vector)
powMatrix (\Np\matrix $m)
powScalar (int|float $s)
powVector (\Np\vector $vector)
substractScalar (int|float $scalar)
subtractMatrix (\Np\matrix $m)
subtractVector (\Np\vector $vector)
Protected Member Functions inherited from Np\core\nd
__construct (public int $ndim, public int $dtype=self::FLOAT)
Additional Inherited Members
Public Attributes inherited from Np\core\nd
$data
const DOUBLE = 2
const EPSILON = 1e-8
const FLOAT = 1
const INT = 3
const TWO_PI = 2. * M_PI
Static Protected Member Functions inherited from Np\core\nd
static _dimensionaMisMatchErr ($msg)
static _dtypeErr ($msg)
static _err ($msg)
static _invalidArgument ($argument)
static _ndDouble (int $size)
static _ndFloat (int $size)
static _ndInt (int $size)
Protected Attributes inherited from Np\core\nd
$_mem = null
$_time = null
Member Function Documentation
add()
Np\vector::add (int|float|matrix|vector $d)
Parameters
int | float | matrix | vector $d
Returns
matrix|vector
addMatrix()
Np\vector::addMatrix (\Np\matrix $m) protected
Parameters
\Np\matrix $m
Returns
matrix
addScalar()
Np\vector::addScalar (int|float $s) protected
Parameters
int | float $s
Returns
vector
addVector()
Np\vector::addVector (\Np\vector $vector) protected
Parameters
\Np\vector $vector
Returns
vector
ar()
static Np\vector::ar (array $data, int $dtype = self::FLOAT) static
Build a new vector from a php array.
Parameters
array $data
int $dtype
Returns
vector
argMax()
Np\vector::argMax ()
Return the index of the maximum element in the vector.
Returns
int
argMin()
Np\vector::argMin ()
Return the index of the minimum element in the vector.
Returns
int
convolve()
Np\vector::convolve (\Np\vector $v, int $stride = 1)
Parameters
\Np\vector $v
int $stride
Returns
vector
divide()
Np\vector::divide (int|float|matrix|vector $d)
Parameters
int | float | matrix | vector $d
Returns
matrix|vector
Referenced by Np\matrix\mean().
divideMatrix()
Np\vector::divideMatrix (\Np\matrix $m) protected
Parameters
\Np\matrix $m
Returns
matrix
divideScalar()
Np\vector::divideScalar (int|float $s) protected
Parameters
int | float $s
Returns
vector
divideVector()
Np\vector::divideVector (vector $v) protected
Parameters
vector $v
Returns
vector
Referenced by Np\vector\reciprocal().
dotMatrix()
Np\vector::dotMatrix (\Np\matrix $m)
Compute the vector-matrix dot product of this vector and matrix .
Parameters
\Np\matrix $m
Returns
vector
factory()
static Np\vector::factory (int $col, int $dtype = self::FLOAT) static
Factory method to build a new vector.
Parameters
int $col
int $dtype
Returns
vector
Referenced by Np\reductions\ref\factory(), Np\decompositions\svd\factory(), and Np\decompositions\lu\factory().
full()
static Np\vector::full (int $col, int|float $val, int $dtype = self::FLOAT) static
create a vector with given scalar value
Parameters
int $col
int | float | double $val
int $dtype
Returns
vector
gaussian()
static Np\vector::gaussian (int $n, int $dtype = self::FLOAT) static
Return a Gaussian random vector with mean 0 and unit variance.
Parameters
int $n
int $dtype
Returns
self
getSize()
Np\vector::getSize ()
get the size of vector
Returns
int
inner()
Np\vector::inner (\Np\vector $vector)
Return the inner product of two vectors.
Parameters
\Np\vector $vector
linspace()
static Np\vector::linspace (float $min, float $max, int $n, int $dtype = self::FLOAT) static
Return a vector of n evenly spaced numbers between minimum and maximum.
Parameters
float $min
float $max
int $n
int $dtype
Exceptions
invalidArgumentException
Returns
vector
mean()
Np\vector::mean ()
Returns
int|float
median()
Np\vector::median ()
Returns
int|float
mod()
Np\vector::mod (int|float|\Np\matrix|\Np\vector $d)
Parameters
int | float | \Np\matrix | \Np\vector $d
Returns
matrix|vector
modMatrix()
Np\vector::modMatrix (\Np\matrix $m) protected
Parameters
\Np\matrix $m
Returns
matrix
modScalar()
Np\vector::modScalar (int|float $s) protected
Parameters
int | float $s
modVector()
Np\vector::modVector (\Np\vector $vector) protected
Parameters
\Np\vector $vector
Returns
vector
multiply()
Np\vector::multiply (int|float|matrix|vector $d)
Parameters
int | float | matrix | vector $d
Returns
matrix|vector
multiplyMatrix()
Np\vector::multiplyMatrix (\Np\matrix $m) protected
Parameters
\Np\matrix $m
Returns
matrix
multiplyScalar()
Np\vector::multiplyScalar (int|float $s) protected
Parameters
int | float $s
Returns
vector
multiplyVector()
Np\vector::multiplyVector (\Np\vector $vector) protected
Parameters
\Np\vector $vector
Returns
vector
normL1()
Np\vector::normL1 ()
Calculate the L1 norm of the vector.
Returns
float
null()
static Np\vector::null (int $col, int $dtype = self::FLOAT) static
create a null like vector
Parameters
int $col
Returns
vector
ones()
static Np\vector::ones (int $col, int $dtype = self::FLOAT) static
create one like vector
Parameters
int $col
Returns
vector
poisson()
static Np\vector::poisson (int $n, float $lambda = 1.0, int $dtype = self::FLOAT) static
Generate a vector with n elements from a Poisson distribution.
Parameters
int $n
float $lambda
int $dtype
Returns
vector
pow()
Np\vector::pow (int|float|\Np\matrix|\Np\vector $d)
Parameters
int | float | \Np\matrix | \Np\vector $d
Returns
matrix|vector
powMatrix()
Np\vector::powMatrix (\Np\matrix $m) protected
Parameters
\Np\matrix $m
Returns
matrix
powScalar()
Np\vector::powScalar (int|float $s) protected
Parameters
int | float $s
Returns
vector
powVector()
Np\vector::powVector (\Np\vector $vector) protected
Parameters
\Np\vector $vector
Returns
vector
product()
Np\vector::product ()
Return the product of the vector.
Returns
int|float
randn()
static Np\vector::randn (int $col, int $dtype = self::FLOAT) static
Return vector with random values
Parameters
int $col
int $dtype
Returns
vector
range()
static Np\vector::range (int|float $start, int|float $end, int|float $interval = 1, int $dtype = self::FLOAT) static
Return evenly spaced values within a given interval.
Parameters
int | float $start
int | float $end
int | float $interval
int $dtype
Returns
vector
reciprocal()
Np\vector::reciprocal ()
Return the reciprocal of the vector element-wise.
Returns
self
References Np\vector\divideVector().
setData()
Np\vector::setData (int|float|array $data)
set data to vector
Parameters
int | float | array $data
sort()
Np\vector::sort ($type = 'i')
sort the vector
Parameters
string $type i or d
square()
Np\vector::square ()
Returns
vector
substractScalar()
Np\vector::substractScalar (int|float $scalar) protected
Parameters
\Np\vector $scalar
Returns
subtract()
Np\vector::subtract (int|float|matrix|vector $d)
Parameters
int | float | matrix | vector $d
Returns
matrix|vector
subtractMatrix()
Np\vector::subtractMatrix (\Np\matrix $m) protected
Parameters
\Np\matrix $m
Returns
matrix
subtractVector()
Np\vector::subtractVector (\Np\vector $vector) protected
Parameters
\Np\vector $vector
Returns
vector
sum()
Np\vector::sum ()
The sum of the vector.
Returns
float
uniform()
static Np\vector::uniform (int $col, int $dtype = self::FLOAT) static
Return vector with uniform values
Parameters
int $col
int $dtype
Returns
vector
zeros()
static Np\vector::zeros (int $col, int $dtype = self::FLOAT) static
Build a vector of zeros with n elements.
Parameters
int $col
int $dtype
Returns
vector
The documentation for this class was generated from the following file:
/home/ghost/projects/git/numphp/src/vector.php