Numerical Processing: Np\decompositions\svd Class Reference
Np\decompositions\svd Class Reference
Public Member Functions
s ()
u ()
v ()
vt ()
Static Public Member Functions
static factory (\Np\matrix $m)
Protected Member Functions
__construct (protected \Np\matrix $u, protected \Np\matrix $v, protected \Np\vector $s)
Constructor & Destructor Documentation
__construct()
Np\decompositions\svd::__construct (protected \Np\matrix $u, protected \Np\matrix $v, protected \Np\vector $s) protected
Parameters
\Np\matrix $u
\Np\matrix $v
\Np\vector $s
Member Function Documentation
factory()
static Np\decompositions\svd::factory (\Np\matrix $m) static
Parameters
matrix $m
Returns
self
References Np\vector\factory(), Np\matrix\factory(), and Np\core\lapack\gesdd().
s()
Np\decompositions\svd::s ()
Return the singular values of matrix.
Returns
vector
u()
Np\decompositions\svd::u ()
Return the U matrix.
Returns
matrix
v()
Np\decompositions\svd::v ()
Return the V matrix.
Returns
matrix
Referenced by Np\decompositions\svd\vt().
vt()
Np\decompositions\svd::vt ()
Return the V transposed matrix.
Returns
matrix
References Np\decompositions\svd\v().
The documentation for this class was generated from the following file:
/home/ghost/projects/git/numphp/src/decompositions/svd.php