Numerical Processing: Np\matrix Class Reference
Np\matrix Class Reference
Public Member Functions
__toString ()
addScaleRow (int $r1, int $r2, float $c)
argMax ()
argMin ()
asArray ()
asVector ()
cholesky ()
colAsVector (int $index)
convolve (matrix $m, int $stride=1)
covariance (vector|null $mean=null)
det ()
diagonalAsVector ()
dignoalInterChange ()
diminish_left (int $cols)
diminish_right (int $cols)
divide (int|float|matrix|vector $d)
eign (bool $symmetric=false)
equal (int|float|matrix|vector $d)
getDiagonalVal (int $i)
getDtype ()
getShape ()
getSize ()
greater (int|float|matrix|vector $d)
has_ZeroRow ()
is_rowZero (int $row)
isSquare ()
isSymmetric ()
joinAbove (matrix $m)
joinBelow (matrix $m)
joinLeft (matrix $m)
joinRight (matrix $m)
less (int|float|matrix $m)
lu ()
mean ()
median ()
mod (int|float|matrix|vector $d)
multiply (int|float|matrix|vector $m)
normFrob ()
normINF ()
normL1 ()
normL2 ()
pow (int|float|matrix|vector $d)
printMatrix ()
reciprocal ()
ref ()
rowAsVector (int $index)
rref ()
scale (int|float $scalar)
scaleCol (int $col, int|float $c)
scaleDigonalCol (int|float $c, bool $lDig=true)
scaleRow (int $row, int|float $c)
setData (int|float|array $data, bool $dignoal=false)
square ()
subtract (int|float|matrix|vector $d)
subtractColumnVector (vector $v)
sum (int|float|matrix|vector $m)
sumRows ()
svd ()
swapCols (int $c1, int $c2)
swapRows (int $r1, int $r2)
swapValue (int $i1, int $i2)
trace ()
transpose ()
variance (vector|null $mean=null)
Public Member Functions inherited from Np\core\nd
checkDimensions (\Np\matrix|\Np\vector $Obj1, \Np\matrix $Obj2)
checkDtype (\Np\matrix|\Np\vector $Obj1, \Np\matrix|\Np\vector $Obj2)
checkShape (\Np\matrix|\Np\vector $Obj1, \Np\matrix|\Np\vector $Obj2)
getMemory ()
time ()
Static Public Member Functions
static ar (array $data, int $dtype=self::FLOAT)
static diagonal (array $elements, int $dtype=self::FLOAT)
static factory (int $row, int $col, int $dtype=self::FLOAT)
static full (int $row, int $col, $val, int $dtype=self::FLOAT)
static gaussian (int $row, int $col, int $dtype=self::FLOAT)
static identity (int $n, int $dtype=self::FLOAT)
static is_zero ($d)
static null (int $row, int $col, int $dtype=self::FLOAT)
static ones (int $row, int $col, int $dtype=self::FLOAT)
static poisson (int $row, int $col, float $lambda=1.0, int $dtype=self::FLOAT)
static randn (int $row, int $col, int $dtype=self::FLOAT)
static uniform (int $row, int $col, int $dtype=self::FLOAT)
static zeros (int $row, int $col, int $dtype=self::FLOAT)
Protected Member Functions
__construct (public int $row, public int $col, int $dtype=self::Float)
divideMatrix (matrix $m)
divideScalar (int|float $s)
divideVector (vector $v)
equalMatrix (matrix $m)
equalScalar (int|float $s)
equalVector (vector $v)
greaterMatrix (matrix $m)
greaterScalar (int|float $s)
greaterVector (vector $v)
modMatrix (matrix $m)
modScalar (int|float $s)
modVector (vector $v)
multiplyMatrix (matrix $m)
multiplyVector (vector $v)
powMatrix (matrix $m)
powScalar (int|float $s)
powVector (vector $v)
subtractMatrix (matrix $m)
subtractScalar (int|float $s)
subtractVector (vector $v)
sumMatrix (matrix $m)
sumScalar (int|float $s)
sumVector (vector $v)
Protected Member Functions inherited from Np\core\nd
__construct (public int $ndim, public int $dtype=self::FLOAT)
Additional Inherited Members
Public Attributes inherited from Np\core\nd
$data
const DOUBLE = 2
const EPSILON = 1e-8
const FLOAT = 1
const INT = 3
const TWO_PI = 2. * M_PI
Static Protected Member Functions inherited from Np\core\nd
static _dimensionaMisMatchErr ($msg)
static _dtypeErr ($msg)
static _err ($msg)
static _invalidArgument ($argument)
static _ndDouble (int $size)
static _ndFloat (int $size)
static _ndInt (int $size)
Protected Attributes inherited from Np\core\nd
$_mem = null
$_time = null
Constructor & Destructor Documentation
__construct()
Np\matrix::__construct (public int $row, public int $col, int $dtype = self::Float) protected
Parameters
int $row
int $col
int $dtype
Returns
$this
Member Function Documentation
addScaleRow()
Np\matrix::addScaleRow (int $r1, int $r2, float $c)
Parameters
int $r1
int $r2
float $c
ar()
static Np\matrix::ar (array $data, int $dtype = self::FLOAT) static
create 2d matrix using php array
Parameters
array $data
int $dtype matrix data type float|double
Returns
argMax()
Np\matrix::argMax ()
Return the index of the maximum element in every row of the matrix.
Returns
int
argMin()
Np\matrix::argMin ()
Return the index of the minimum element in every row of the matrix.
Returns
int
asArray()
Np\matrix::asArray ()
Return the elements of the matrix in a 2-d array.
Returns
array
asVector()
Np\matrix::asVector ()
Flatten i.e unravel the matrix into a vector.
Returns
cholesky()
Np\matrix::cholesky ()
Return the lower triangular matrix of the Cholesky decomposition.
Returns
matrix|null
colAsVector()
Np\matrix::colAsVector (int $index)
Return a col as vector from the matrix.
Parameters
int $index
Returns
convolve()
Np\matrix::convolve (matrix $m, int $stride = 1)
2D convolution between a matrix ma and kernel kb, with a given stride.
Parameters
\Np\matrix $m
int $stride
Returns
matrix
covariance()
Np\matrix::covariance (vector|null $mean = null)
Compute the covariance matrix.
Parameters
vector | null $mean
Returns
matrix
det()
Np\matrix::det ()
Calculate the determinant of the matrix.
Returns
float
diagonal()
static Np\matrix::diagonal (array $elements, int $dtype = self::FLOAT) static
create a diagonal 2d matrix with given 1d array;
Parameters
array $elements
Returns
diagonalAsVector()
Np\matrix::diagonalAsVector ()
Return the diagonal elements of a square matrix as a vector.
Returns
dignoalInterChange()
Np\matrix::dignoalInterChange ()
dignoalInterChange
diminish_left()
Np\matrix::diminish_left (int $cols)
Parameters
int $cols
Returns
diminish_right()
Np\matrix::diminish_right (int $cols)
Parameters
int $cols
Returns
divide()
Np\matrix::divide (int|float|matrix|vector $d)
Return the division of two elements, element-wise.
Parameters
int | float | matrix $d
Returns
matrix
eign()
Np\matrix::eign (bool $symmetric = false)
Compute the eigen decomposition of a general matrix. return the eigenvalues and eigenvectors as object
Parameters
bool $symmetric
Returns
eigen
equal()
Np\matrix::equal (int|float|matrix|vector $d)
Parameters
int | float | matrix | vector $d
Returns
matrix
factory()
static Np\matrix::factory (int $row, int $col, int $dtype = self::FLOAT) static
create empty 2d matrix for given data type
Parameters
int $row num of rows
int $col num of cols
int $dtype matrix data type float|double
Returns
Referenced by Np\decompositions\svd\factory(), and Np\decompositions\lu\factory().
full()
static Np\matrix::full (int $row, int $col, $val, int $dtype = self::FLOAT) static
create a 2d matrix with given scalar value
Parameters
int $row
int $col
int | float | double $val
Returns
gaussian()
static Np\matrix::gaussian (int $row, int $col, int $dtype = self::FLOAT) static
Return a standard normally distributed random matrix i.e values between -1 and 1.
Parameters
int $row
int $col
int $dtype Description
Returns
getDiagonalVal()
Np\matrix::getDiagonalVal (int $i)
get a diagonal value from matrix
Parameters
int $i
Returns
float
getDtype()
Np\matrix::getDtype ()
get the matrix data type
Returns
int
getShape()
Np\matrix::getShape ()
get the shape of matrix
Returns
object
getSize()
Np\matrix::getSize ()
get the number of elements in the matrix.
Returns
int
greater()
Np\matrix::greater (int|float|matrix|vector $d)
Parameters
int | float | matrix | vector $d
Returns
matrix
has_ZeroRow()
Np\matrix::has_ZeroRow ()
Returns
bool
identity()
static Np\matrix::identity (int $n, int $dtype = self::FLOAT) static
create an identity matrix with the given dimensions.
Parameters
int $n
int $dtype
Returns
matrix
Exceptions
is_rowZero()
Np\matrix::is_rowZero (int $row)
is row zero
Parameters
int $row
Returns
bool
is_zero()
static Np\matrix::is_zero ($d) static
Parameters
int | float $d
Returns
bool
isSquare()
Np\matrix::isSquare ()
is matrix squred
Returns
bool
Referenced by Np\decompositions\cholesky\factory(), and Np\decompositions\lu\factory().
isSymmetric()
Np\matrix::isSymmetric ()
Is the matrix symmetric i.e. is it equal to its own transpose?
Returns
bool
joinAbove()
Np\matrix::joinAbove (matrix $m)
Join matrix m Above this matrix.
Parameters
\Np\matrix $m
Returns
matrix
joinBelow()
Np\matrix::joinBelow (matrix $m)
Join matrix m below this matrix.
Parameters
\Np\matrix $m
Returns
matrix
joinLeft()
Np\matrix::joinLeft (matrix $m)
Attach given matrix to the left of this matrix.
Parameters
\Np\matrix $m
Returns
joinRight()
Np\matrix::joinRight (matrix $m)
Join matrix m to the Right of this matrix.
Parameters
\Np\matrix $m
Returns
matrix
less()
Np\matrix::less (int|float|matrix $m)
Parameters
int | float | matrix $m
Returns
matrix
lu()
Np\matrix::lu ()
Compute the LU factorization of matrix. return lower, upper, and permutation matrices as object.
Returns
lu
mean()
Np\matrix::mean ()
Compute the means of each row and return them in a vector.
Returns
vector
References Np\vector\divide().
median()
Np\matrix::median ()
Return the median vector of this matrix.
Returns
vector
mod()
Np\matrix::mod (int|float|matrix|vector $d)
Calculate the modulus i.e remainder of division between this matrix and another matrix.
Parameters
int | float | matrix | vector $d
Returns
matrix
multiply()
Np\matrix::multiply (int|float|matrix|vector $m)
multiply this matrix with another matrix|scalar element-wise Matrix Scalar multiplication
Parameters
int | float | matrix | vector $m
Returns
matrix|vector
multiplyMatrix()
Np\matrix::multiplyMatrix (matrix $m) protected
Parameters
\Np\matrix $m
Returns
matrix
multiplyVector()
Np\matrix::multiplyVector (vector $v) protected
Parameters
\Np\vector $v
Returns
matrix
normFrob()
Np\matrix::normFrob ()
Return the Frobenius norm of the matrix.
Returns
float
normINF()
Np\matrix::normINF ()
Return the L1 norm of the matrix.
Returns
float
normL1()
Np\matrix::normL1 ()
Return the L1 norm of the matrix.
Returns
float
normL2()
Np\matrix::normL2 ()
Return the L2 norm of the matrix.
Returns
float
null()
static Np\matrix::null (int $row, int $col, int $dtype = self::FLOAT) static
create a null like 2d matrix
Parameters
int $row
int $col
Returns
ones()
static Np\matrix::ones (int $row, int $col, int $dtype = self::FLOAT) static
create one like 2d matrix
Parameters
int $row
int $col
Returns
poisson()
static Np\matrix::poisson (int $row, int $col, float $lambda = 1.0, int $dtype = self::FLOAT) static
Generate a m x n matrix with elements from a Poisson distribution.
Parameters
int $row
int $col
float $lambda
int $dtype
Returns
pow()
Np\matrix::pow (int|float|matrix|vector $d)
Raise this matrix to the power of the element-wise entry in another matrix.
Parameters
int | float | matrix $m
Returns
matrix
printMatrix()
Np\matrix::printMatrix ()
print the matrix in consol
randn()
static Np\matrix::randn (int $row, int $col, int $dtype = self::FLOAT) static
Create Matrix with random values
Parameters
int $row
int $col
int $dtype Float|Double
Returns
reciprocal()
Np\matrix::reciprocal ()
Return the element-wise reciprocal of the matrix.
Returns
matrix
ref()
Np\matrix::ref ()
Calculate the row echelon form of the matrix. Return the reduced matrix.
Returns
matrix|null
rowAsVector()
Np\matrix::rowAsVector (int $index)
Return a row as vector from the matrix.
Parameters
int $index
Returns
rref()
Np\matrix::rref ()
FIXME-----------— RREF The reduced row echelon form (RREF) of a matrix.
Returns
scale()
Np\matrix::scale (int|float $scalar)
Parameters
int | float $scalar
Returns
matrix
scaleCol()
Np\matrix::scaleCol (int $col, int|float $c)
scale all the elements of
Parameters
int $col
int | float $c
scaleDigonalCol()
Np\matrix::scaleDigonalCol (int|float $c, bool $lDig = true)
Scale digonally
Parameters
int | float $c
bool $lDig
scaleRow()
Np\matrix::scaleRow (int $row, int|float $c)
scale all the elements of a row
Parameters
int $row
int | float $c
setData()
Np\matrix::setData (int|float|array $data, bool $dignoal = false)
Set given data in matrix
Parameters
int | float | array $data
bool $dignoal
Returns
void
square()
Np\matrix::square ()
Square of matrix
Returns
matrix
subtract()
Np\matrix::subtract (int|float|matrix|vector $d)
subtract another matrix, vector or a scalar to this matrix
Parameters
int | float | matrix | vector $d matrix|$scalar to subtract this matrix
Returns
subtractColumnVector()
Np\matrix::subtractColumnVector (vector $v)
Parameters
vector $v
Returns
matrix
subtractMatrix()
Np\matrix::subtractMatrix (matrix $m) protected
Parameters
matrix $m
Returns
matrix
subtractVector()
Np\matrix::subtractVector (vector $v) protected
Parameters
vector $v
Returns
matrix
sum()
Np\matrix::sum (int|float|matrix|vector $m)
Sum of two matrix, vector or a scalar to current matrix
Parameters
int | float | matrix | vector $m
Returns
matrix
sumRows()
Np\matrix::sumRows ()
Sum of Rows of matrix
Returns
vector
svd()
Np\matrix::svd ()
Compute the singular value decomposition of a matrix and return an object of the singular values and unitary matrices
Returns
object (u,s,v)
swapCols()
Np\matrix::swapCols (int $c1, int $c2)
swap specific cols in matrix
Parameters
int $c1
int $c2
swapRows()
Np\matrix::swapRows (int $r1, int $r2)
swap specific rows in matrix
Parameters
int $r1
int $r2
Referenced by Np\reductions\rref\factory().
swapValue()
Np\matrix::swapValue (int $i1, int $i2)
swap specific values in matrix
Parameters
int $i1
int $i2
trace()
Np\matrix::trace ()
Return the trace of the matrix i.e the sum of all diagonal elements of a square matrix.
Returns
float
transpose()
Np\matrix::transpose ()
Transpose the matrix i.e row become cols and cols become rows.
Returns
Referenced by Np\decompositions\eigen\eigenVec().
uniform()
static Np\matrix::uniform (int $row, int $col, int $dtype = self::FLOAT) static
Return 2d matrix with uniform values
Parameters
int $row
int $col
int $dtype
Returns
variance()
Np\matrix::variance (vector|null $mean = null)
Compute the row variance of the matrix.
Parameters
vector | null $mean
Returns
vector
zeros()
static Np\matrix::zeros (int $row, int $col, int $dtype = self::FLOAT) static
Return a zero matrix with the given dimensions.
Parameters
int $row
int $col
int $dtype
Returns
The documentation for this class was generated from the following file:
/home/ghost/projects/git/numphp/src/matrix.php