Numerical Processing: Np\decompositions\lu Class Reference
Np\decompositions\lu Class Reference
Public Member Functions
l ()
p ()
u ()
Static Public Member Functions
static factory (matrix $m)
Protected Member Functions
__construct (protected matrix $l, protected matrix $u, protected matrix $p)
Constructor & Destructor Documentation
__construct()
Np\decompositions\lu::__construct (protected matrix $l, protected matrix $u, protected matrix $p) protected
Parameters
matrix $l
matrix $u
matrix $p
Member Function Documentation
factory()
static Np\decompositions\lu::factory (matrix $m) static
Parameters
matrix $m
Returns
self
Exceptions
InvalidArgumentException
References Np\vector\factory(), Np\matrix\factory(), Np\core\lapack\getrf(), and Np\matrix\isSquare().
l()
Np\decompositions\lu::l ()
Return the lower triangular matrix.
Returns
matrix
p()
Np\decompositions\lu::p ()
Return the permutation matrix.
Returns
matrix
u()
Np\decompositions\lu::u ()
Return the upper triangular matrix.
Returns
matrix
The documentation for this class was generated from the following file:
/home/ghost/projects/git/numphp/src/decompositions/lu.php